CREATE TABLE request (
                         id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                         topic text NOT NULL,
                         description text NOT NULL,
                         request_user_id int8 NOT NULL,
                         equipment_id int8 NULL,
                         executor_user_id int8 NULL,
                         executor_comments text NULL,
                         request_status_id int8 NULL,
                         created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
                         ,CONSTRAINT request_pkey PRIMARY KEY (id)
--                          ,CONSTRAINT request_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON UPDATE CASCADE,
--                          CONSTRAINT request_executor_user_id_fkey FOREIGN KEY (executor_user_id) REFERENCES users(id) ON UPDATE CASCADE,
--                          CONSTRAINT request_request_status_id_fkey FOREIGN KEY (request_status_id) REFERENCES request_status(id) ON UPDATE CASCADE,
--                          CONSTRAINT request_request_user_id_fkey FOREIGN KEY (request_user_id) REFERENCES users(id) ON UPDATE CASCADE
);

CREATE TABLE request_status (
                                id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                title text NOT NULL,
                                CONSTRAINT request_status_pkey PRIMARY KEY (id)
);
INSERT INTO request_status (title) VALUES
                                              ('Создано'),
                                              ('Назначено'),
                                              ('В работе'),
                                              ('Выполнено');
INSERT INTO request (topic,description,request_user_id,equipment_id,executor_user_id,executor_comments,request_status_id,created_at,updated_at) VALUES
    ('Не работает мышь','Не работает тварь!',2,2,NULL,NULL,1,'2023-06-02 08:22:50','2023-06-02 08:22:50');

